import os

DATABASE_NAME = os.getenv('DATABASE_NAME')
DATABASE_USER = os.getenv('DATABASE_USER')
DATABASE_PASSWORD = os.getenv('DATABASE_PASSWORD')
DATABASE_HOST = os.getenv('DATABASE_HOST')
DATABASE_SOCKET = os.getenv('DATABASE_SOCKET')


class Config:
    SQLALCHEMY_DATABASE_URI = f"mysql+pymysql://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}/{DATABASE_NAME}?unix_socket={DATABASE_SOCKET}"
    FLASK_DEBUG=os.environ.get("FLASK_DEBUG") or True

    RABBITMQ_URL = os.environ.get("RABBITMQ_URL")
    RABBITMQ_EXCHANGE = os.environ.get("RABBITMQ_EXCHANGE")
    RABBITMQ_EXCHANGE_TYPE = os.environ.get("RABBITMQ_EXCHANGE_TYPE")
    RABBITMQ_ROUTING_KEY = os.environ.get("RABBITMQ_ROUTING_KEY")