"""Initial setup for API testing, no relationships

Revision ID: ad7c6eadf844
Revises: 
Create Date: 2025-09-15 01:37:34.915413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad7c6eadf844'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36, collation='utf8mb4_bin'), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('date_joined', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('profile_image_url', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
